/* ============================================================
   HHpro - Psychrometric report PDF
   ------------------------------------------------------------
   Builds a one-or-more page Letter PDF for a psychrometric
   calculation: title, the chart (converted from the same SVG the
   page draws, as vector line work), then the input/result blocks.

     HHpro.PsychroPdf.build({
         title: 'Project Alpha - AHU-1 mixed air',
         subtitle: 'HHpro Psychrometrics · Sep 11, 2026 · 780 ft',
         blocks: [
             { title: 'Airflow', rows: [['Total airflow', '10,000 CFM'], ...] },
             { title: 'Air properties', table: { head: [...], rows: [[...], ...] } }
         ],
         svg: svgElement,
         footer: 'Generated by HHpro'
     }) -> Blob (application/pdf)

   Self-contained writer (no library): standard Helvetica fonts
   with WinAnsi encoding, one content stream per page, a simple
   xref table. The SVG conversion understands exactly what
   psychro_chart.js emits: rect, line, path (M/L), polygon,
   circle, text (with text-anchor and translate/rotate), groups
   with clip-path, and marker-end arrowheads. Colours come from a
   print palette keyed by the chart's CSS classes, so the PDF is
   dark-on-white regardless of the site theme.
   ============================================================ */

(function () {
    'use strict';
    window.HHpro = window.HHpro || {};

    // ---------------- Helvetica metrics (AFM widths, /1000) ----------------
    var HELV = [278, 278, 355, 556, 556, 889, 667, 191, 333, 333, 389, 584, 278, 333, 278, 278,
        556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 278, 278, 584, 584, 584, 556,
        1015, 667, 667, 722, 722, 667, 611, 778, 722, 278, 500, 667, 556, 833, 722, 778,
        667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 278, 278, 278, 469, 556,
        333, 556, 556, 500, 556, 556, 278, 556, 556, 222, 222, 500, 222, 833, 556, 556,
        556, 556, 333, 500, 278, 556, 500, 722, 500, 500, 500, 334, 260, 334, 584];
    var HELV_BOLD = [278, 333, 474, 556, 556, 889, 722, 238, 333, 333, 389, 584, 278, 333, 278, 278,
        556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 333, 333, 584, 584, 584, 611,
        975, 722, 722, 722, 722, 667, 611, 778, 722, 278, 556, 722, 611, 833, 722, 778,
        667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 333, 278, 333, 584, 556,
        333, 556, 611, 556, 611, 556, 333, 611, 611, 278, 278, 556, 278, 889, 611, 611,
        611, 611, 389, 556, 333, 611, 556, 778, 556, 556, 500, 389, 280, 389, 584];

    function textWidth(str, size, bold) {
        var tbl = bold ? HELV_BOLD : HELV, w = 0;
        for (var i = 0; i < str.length; i++) {
            var c = str.charCodeAt(i);
            w += (c >= 32 && c <= 126) ? tbl[c - 32] : 556;
        }
        return w * size / 1000;
    }

    // Map to WinAnsi-safe text: the few symbols the page uses that are
    // outside Latin-1 get ASCII stand-ins.
    function sanitize(str) {
        return String(str)
            .replace(/→/g, '->').replace(/←/g, '<-')
            .replace(/−/g, '-').replace(/–|—/g, '-')
            .replace(/’/g, "'").replace(/“|”/g, '"')
            .replace(/…/g, '...').replace(/✓|✔/g, 'OK').replace(/✗|✘/g, 'X')
            .replace(/∞/g, 'inf').replace(/Δ/g, 'd');
    }

    function pdfString(str) {
        var s = sanitize(str), out = '';
        for (var i = 0; i < s.length; i++) {
            var c = s.charCodeAt(i);
            if (c > 255) c = 63; // '?'
            if (c === 40 || c === 41 || c === 92) out += '\\' + String.fromCharCode(c);
            else if (c < 32 || c > 126) out += '\\' + ('00' + c.toString(8)).slice(-3);
            else out += String.fromCharCode(c);
        }
        return '(' + out + ')';
    }

    function num(n) {
        return (Math.round(n * 100) / 100).toString();
    }

    function hexToRgb(hex) {
        var h = hex.replace('#', '');
        if (h.length === 3) h = h[0] + h[0] + h[1] + h[1] + h[2] + h[2];
        var n = parseInt(h, 16);
        return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
    }

    function rgbOp(hex, stroke) {
        var c = hexToRgb(hex);
        return num(c[0]) + ' ' + num(c[1]) + ' ' + num(c[2]) + (stroke ? ' RG' : ' rg');
    }

    // ---------------- print palette for the chart ----------------
    var STYLES = {
        'psy-frame':          { fill: '#ffffff' },
        'psy-frame-outline':  { stroke: '#444444', width: 0.8 },
        'psy-grid-line':      { stroke: '#dddddd', width: 0.35 },
        'psy-grid-major':     { stroke: '#c4c4c4', width: 0.5 },
        'psy-tick':           { stroke: '#444444', width: 0.7 },
        'psy-axis-label':     { text: '#333333', size: 11 },
        'psy-axis-title':     { text: '#111111', size: 12, bold: true },
        'psy-pressure-label': { text: '#555555', size: 11 },
        'psy-sat':            { stroke: '#000000', width: 1.6 },
        'psy-rh':             { stroke: '#1f6fb0', width: 0.7 },
        'psy-wb':             { stroke: '#1f8f5f', width: 0.55 },
        'psy-h':              { stroke: '#a67c00', width: 0.55, dash: [5, 4] },
        'psy-v':              { stroke: '#6a4fb5', width: 0.55, dash: [2, 3] },
        'psy-label':          { size: 10 },
        'psy-label-rh':       { text: '#1f6fb0' },
        'psy-label-wb':       { text: '#1f8f5f' },
        'psy-label-h':        { text: '#8a6600' },
        'psy-label-v':        { text: '#6a4fb5' },
        'psy-label-caption':  { size: 10 },
        'psy-h-fine':         { stroke: '#d9c27a', width: 0.3, dash: null },
        'psy-h-tick':         { stroke: '#a67c00', width: 0.7 },
        'psy-h-edge-label':   { size: 10 },
        'psy-prot-bg':        { fill: '#ffffff', stroke: '#b9c0c8', width: 0.6 },
        'psy-prot-line':      { stroke: '#000000', width: 0.8 },
        'psy-prot-tick':      { stroke: '#444444', width: 0.5 },
        'psy-prot-label':     { text: '#444444', size: 7 },
        'psy-prot-label-shr': { text: '#000000' },
        'psy-prot-caption':   { text: '#000000', size: 7, bold: true },
        'psy-rscale-box':     { fill: '#f7f8fa', stroke: '#c9ced4', width: 0.5 },
        'psy-rscale-bar':     { stroke: '#444444', width: 0.8 },
        'psy-rscale-tick':    { stroke: '#444444', width: 0.5 },
        'psy-rscale-label':   { text: '#333333', size: 9 },
        'psy-rscale-caption': { text: '#111111', size: 9, bold: true },
        'psy-shr-ref':        { stroke: '#000000', width: 1.0 },
        'psy-line':          { stroke: '#000000', width: 1.6 },
        'psy-line-mix':       { stroke: '#666666', dash: [6, 4] },
        'psy-line-process':   { stroke: '#000000' },
        'psy-line-reheat':    { stroke: '#c0304a' },
        'psy-path':           { stroke: '#000000', width: 1.2 },
        'psy-line-room':      { stroke: '#7b3fbf', dash: [5, 3] },
        'psy-line-econ':      { stroke: '#1f8f5f', width: 1.2, dash: [6, 4] },
        'psy-line-limit':     { stroke: '#c27c00', width: 1.0, dash: [2, 3] },
        'psy-region':         { fill: '#000000', stroke: null, width: 0 },
        'psy-econ-region':    { fill: '#9fd8bd', stroke: null },
        'psy-path-label':     { size: 10, bold: true },
        'psy-callout-bg':     { fill: '#f4f6f8', stroke: '#b9c0c8', width: 0.6 },
        'psy-callout-title':  { text: '#111111', size: 9.5, bold: true },
        'psy-callout-text':   { text: '#222222', size: 9 },
        'psy-callout-req':    { color: '#5f3dc4' },
        'psy-callout-dot':    { color: '#999999' },
        'is-ok':              { color: '#2f9e44' },
        'is-no':              { color: '#e03131' },
        'psy-point-sf': { color: '#868e96' },
        'psy-label-econ':     { text: '#1f8f5f' },
        'psy-label-limit':    { text: '#a86a00' },
        'psy-point-label':    { size: 12, bold: true },
        'psy-point-oa': { color: '#e8590c' }, 'psy-point-er': { color: '#d9480f' },
        'psy-point-ra': { color: '#1c7ed6' }, 'psy-point-ma': { color: '#2f9e44' },
        'psy-point-ph': { color: '#e67700' }, 'psy-point-f1': { color: '#868e96' },
        'psy-point-sa': { color: '#ae3ec9' }, 'psy-point-f2': { color: '#868e96' },
        'psy-point-rh': { color: '#e03131' }, 'psy-point-hu': { color: '#0b7285' },
        'psy-point-ec': { color: '#0ca678' }, 'psy-point-rm': { color: '#5f3dc4' },
        'psy-point-c0': { color: '#1c7ed6' }, 'psy-point-c1': { color: '#e8590c' },
        'psy-point-c2': { color: '#2f9e44' }, 'psy-point-c3': { color: '#ae3ec9' },
        'psy-point-c4': { color: '#e67700' }, 'psy-point-c5': { color: '#e03131' }
    };

    function styleFor(node, inherited) {
        var st = {};
        Object.keys(inherited || {}).forEach(function (k) { st[k] = inherited[k]; });
        var cls = (node.getAttribute && node.getAttribute('class')) || '';
        cls.split(/\s+/).forEach(function (c) {
            var s = STYLES[c];
            if (!s) return;
            Object.keys(s).forEach(function (k) { st[k] = s[k]; });
        });
        return st;
    }

    // ---------------- SVG -> PDF operators ----------------

    function svgToOps(svg, x0, yTop, scale) {
        var ops = [];
        var clips = {};
        Array.prototype.forEach.call(svg.querySelectorAll('clipPath'), function (cp) {
            var poly = cp.querySelector('polygon');
            var rect = cp.querySelector('rect');
            if (poly) {
                clips[cp.id] = { poly: poly.getAttribute('points') };
            } else if (rect) {
                clips[cp.id] = { rect: [+rect.getAttribute('x'), +rect.getAttribute('y'), +rect.getAttribute('width'), +rect.getAttribute('height')] };
            }
        });

        function X(x) { return x0 + x * scale; }
        function Y(y) { return yTop - y * scale; }

        function clipOps(ref) {
            var m = /url\(#([^)]+)\)/.exec(ref || '');
            if (!m || !clips[m[1]]) return null;
            var c = clips[m[1]];
            if (c.rect) {
                return num(X(c.rect[0])) + ' ' + num(Y(c.rect[1] + c.rect[3])) + ' ' + num(c.rect[2] * scale) + ' ' + num(c.rect[3] * scale) + ' re W n';
            }
            var pts = c.poly.trim().split(/\s+/).map(function (p) { return p.split(',').map(Number); });
            var d = pts.map(function (p, i) { return num(X(p[0])) + ' ' + num(Y(p[1])) + (i ? ' l' : ' m'); }).join(' ');
            return d + ' h W n';
        }

        function strokeSetup(st) {
            var s = [];
            s.push(rgbOp(st.stroke || '#000000', true));
            s.push(num((st.width || 1) * scale) + ' w');
            if (st.dash) s.push('[' + st.dash.map(function (d) { return num(d * scale); }).join(' ') + '] 0 d');
            else s.push('[] 0 d');
            return s.join(' ');
        }

        function walk(node, inherited) {
            var tag = node.tagName ? node.tagName.toLowerCase() : '';
            if (tag === 'defs' || tag === 'title' || tag === 'clippath') return;
            if (node.getAttribute && node.getAttribute('visibility') === 'hidden') return;
            var cls = (node.getAttribute && node.getAttribute('class')) || '';
            if (/\bpsy-hover\b|\bpsy-crosshair/.test(cls)) return;
            var st = styleFor(node, inherited);
            var color = st.color; // point colour, inherited from the point group

            if (tag === 'g' || tag === 'svg') {
                var clip = node.getAttribute && clipOps(node.getAttribute('clip-path'));
                if (clip) ops.push('q ' + clip);
                Array.prototype.forEach.call(node.childNodes, function (ch) {
                    if (ch.nodeType === 1) walk(ch, st);
                });
                if (clip) ops.push('Q');
                return;
            }

            if (tag === 'rect') {
                var rx = +node.getAttribute('x'), ry = +node.getAttribute('y');
                var rw = +node.getAttribute('width'), rh = +node.getAttribute('height');
                var re = num(X(rx)) + ' ' + num(Y(ry + rh)) + ' ' + num(rw * scale) + ' ' + num(rh * scale) + ' re';
                if (st.fill && /\bpsy-region\b/.test(cls)) {
                    ops.push('q /GA gs ' + rgbOp(st.fill, false) + ' ' + re + ' f Q ' + rgbOp('#1f8f5f', true) + ' 0.5 w [] 0 d ' + re + ' S');
                    return;
                }
                if (st.fill) ops.push(rgbOp(st.fill, false) + ' ' + re + ' f');
                if (st.stroke) ops.push(strokeSetup(st) + ' ' + re + ' S');
                return;
            }

            if (tag === 'line') {
                var lx1 = +node.getAttribute('x1'), ly1 = +node.getAttribute('y1');
                var lx2 = +node.getAttribute('x2'), ly2 = +node.getAttribute('y2');
                if (!st.stroke) st.stroke = '#000000';
                ops.push(strokeSetup(st) + ' ' + num(X(lx1)) + ' ' + num(Y(ly1)) + ' m ' + num(X(lx2)) + ' ' + num(Y(ly2)) + ' l S');
                if (node.getAttribute('marker-end')) {
                    // Arrowhead: 10 px long, 10 px wide triangle at the end.
                    var ang = Math.atan2(ly2 - ly1, lx2 - lx1), L = 10, Wd = 5;
                    var bx = lx2 - L * Math.cos(ang), by = ly2 - L * Math.sin(ang);
                    var px = -Math.sin(ang) * Wd, py = Math.cos(ang) * Wd;
                    ops.push(rgbOp(st.stroke, false) + ' ' +
                        num(X(lx2)) + ' ' + num(Y(ly2)) + ' m ' +
                        num(X(bx + px)) + ' ' + num(Y(by + py)) + ' l ' +
                        num(X(bx - px)) + ' ' + num(Y(by - py)) + ' l h f');
                }
                return;
            }

            if (tag === 'path') {
                var d = node.getAttribute('d') || '';
                var tokens = d.match(/[ML]|-?[\d.]+/g) || [];
                var out = [], i = 0;
                while (i < tokens.length) {
                    var t = tokens[i];
                    if (t === 'M' || t === 'L') {
                        var px1 = parseFloat(tokens[i + 1]), py1 = parseFloat(tokens[i + 2]);
                        out.push(num(X(px1)) + ' ' + num(Y(py1)) + (t === 'M' ? ' m' : ' l'));
                        i += 3;
                    } else { i++; }
                }
                if (!out.length) return;
                if (st.fill && /\bpsy-region\b/.test(cls)) {
                    // Translucent fill (ExtGState GA = 30% alpha), no stroke.
                    ops.push('q /GA gs ' + rgbOp(st.fill, false) + ' ' + out.join(' ') + ' h f Q');
                    return;
                }
                if (!st.stroke) st.stroke = '#000000';
                ops.push(strokeSetup(st) + ' ' + out.join(' ') + ' S');
                return;
            }

            if (tag === 'circle') {
                if (/psy-point-halo/.test(cls)) return;
                var cx = +node.getAttribute('cx'), cy = +node.getAttribute('cy'), r = +node.getAttribute('r') * scale;
                var k = 0.5523 * r, CX = X(cx), CY = Y(cy);
                var arc = num(CX + r) + ' ' + num(CY) + ' m ' +
                    num(CX + r) + ' ' + num(CY + k) + ' ' + num(CX + k) + ' ' + num(CY + r) + ' ' + num(CX) + ' ' + num(CY + r) + ' c ' +
                    num(CX - k) + ' ' + num(CY + r) + ' ' + num(CX - r) + ' ' + num(CY + k) + ' ' + num(CX - r) + ' ' + num(CY) + ' c ' +
                    num(CX - r) + ' ' + num(CY - k) + ' ' + num(CX - k) + ' ' + num(CY - r) + ' ' + num(CX) + ' ' + num(CY - r) + ' c ' +
                    num(CX + k) + ' ' + num(CY - r) + ' ' + num(CX + r) + ' ' + num(CY - k) + ' ' + num(CX + r) + ' ' + num(CY) + ' c h';
                var fillC = color || '#1c7ed6';
                ops.push(rgbOp(fillC, false) + ' ' + rgbOp('#ffffff', true) + ' ' + num(1.2 * scale) + ' w [] 0 d ' + arc + ' B');
                return;
            }

            if (tag === 'text') {
                var str = sanitize(node.textContent || '');
                if (!str) return;
                var size = (st.size || 10) * scale;
                var bold = !!st.bold;
                var tw = textWidth(str, size, bold);
                var anchor = node.getAttribute('text-anchor') || 'start';
                var tx = +node.getAttribute('x') || 0, ty = +node.getAttribute('y') || 0;
                var textColor = st.text || color || '#222222';
                var transform = node.getAttribute('transform');
                var mtx;
                if (transform) {
                    var tr = /translate\(\s*(-?[\d.]+)[\s,]+(-?[\d.]+)\s*\)/.exec(transform);
                    var rot = /rotate\(\s*(-?[\d.]+)/.exec(transform);
                    var ox = tr ? +tr[1] : 0, oy = tr ? +tr[2] : 0;
                    var deg = rot ? +rot[1] : 0;
                    // SVG rotates clockwise (y down); PDF rotates counter-clockwise.
                    var rad = -deg * Math.PI / 180;
                    var cosr = Math.cos(rad), sinr = Math.sin(rad);
                    var shift = anchor === 'middle' ? -tw / 2 : (anchor === 'end' ? -tw : 0);
                    var sx = X(ox) + shift * cosr, sy = Y(oy) + shift * sinr;
                    mtx = [cosr, sinr, -sinr, cosr, sx, sy];
                } else {
                    var shiftX = anchor === 'middle' ? -tw / 2 : (anchor === 'end' ? -tw : 0);
                    mtx = [1, 0, 0, 1, X(tx) + shiftX, Y(ty)];
                }
                ops.push('BT ' + rgbOp(textColor, false) + ' /' + (bold ? 'F2' : 'F1') + ' ' + num(size) + ' Tf ' +
                    mtx.map(num).join(' ') + ' Tm ' + pdfString(str) + ' Tj ET');
                return;
            }
        }

        walk(svg, {});
        return ops.join('\n');
    }

    // ---------------- page layout ----------------

    var PAGE_W = 612, PAGE_H = 792, MARGIN = 40;
    var CONTENT_W = PAGE_W - 2 * MARGIN;

    function build(spec) {
        var pages = [];      // array of op arrays
        var page = [];
        var y = PAGE_H - MARGIN;

        function newPage() {
            pages.push(page);
            page = [];
            y = PAGE_H - MARGIN;
        }

        function textLine(x, yy, str, size, bold, color) {
            page.push('BT ' + rgbOp(color || '#111111', false) + ' /' + (bold ? 'F2' : 'F1') + ' ' + num(size) + ' Tf ' +
                num(x) + ' ' + num(yy) + ' Td ' + pdfString(str) + ' Tj ET');
        }

        function rule(x1, yy, x2, color, width) {
            page.push(rgbOp(color || '#bbbbbb', true) + ' ' + num(width || 0.5) + ' w [] 0 d ' + num(x1) + ' ' + num(yy) + ' m ' + num(x2) + ' ' + num(yy) + ' l S');
        }

        function fitText(str, size, bold, maxW) {
            str = sanitize(str);
            if (textWidth(str, size, bold) <= maxW) return str;
            while (str.length > 1 && textWidth(str + '...', size, bold) > maxW) str = str.slice(0, -1);
            return str + '...';
        }

        // Header
        textLine(MARGIN, y - 14, spec.title || 'Psychrometric calculation', 15, true);
        y -= 20;
        if (spec.subtitle) {
            textLine(MARGIN, y - 10, spec.subtitle, 9, false, '#555555');
            y -= 14;
        }
        rule(MARGIN, y - 4, PAGE_W - MARGIN, '#999999', 0.8);
        y -= 12;

        // Chart
        if (spec.svg) {
            var vb = (spec.svg.getAttribute('viewBox') || '0 0 980 640').split(/\s+/).map(Number);
            var scale = CONTENT_W / vb[2];
            var chartH = vb[3] * scale;
            page.push('q ' + svgToOps(spec.svg, MARGIN, y, scale) + ' Q');
            y -= chartH + 12;
        }

        // Key/value blocks flow in two columns; tables take the full width.
        var colW = (CONTENT_W - 16) / 2;
        var kvBlocks = (spec.blocks || []).filter(function (b) { return b.rows; });
        var tableBlocks = (spec.blocks || []).filter(function (b) { return b.table; });

        function blockHeight(b) {
            return 14 + b.rows.length * 11 + 8;
        }

        var col = [y, y];
        var colX = [MARGIN, MARGIN + colW + 16];
        kvBlocks.forEach(function (b) {
            var c = col[0] >= col[1] ? 0 : 1;
            var hNeeded = blockHeight(b);
            if (col[c] - hNeeded < MARGIN) {
                // Neither column fits: new page, restart both columns.
                if (Math.max(col[0], col[1]) - hNeeded < MARGIN || Math.min(col[0], col[1]) - hNeeded < MARGIN) {
                    newPage();
                    col = [y, y];
                    c = 0;
                }
            }
            var yy = col[c], x = colX[c];
            textLine(x, yy - 10, b.title.toUpperCase(), 8, true, '#444444');
            rule(x, yy - 13, x + colW, '#cccccc', 0.5);
            yy -= 16;
            b.rows.forEach(function (r) {
                var k = fitText(String(r[0]), 8.5, false, colW * 0.55);
                var v = fitText(String(r[1]), 8.5, false, colW * 0.6);
                textLine(x, yy - 8, k, 8.5, false, '#333333');
                var vw = textWidth(v, 8.5, false);
                textLine(x + colW - vw, yy - 8, v, 8.5, false, '#000000');
                yy -= 11;
            });
            col[c] = yy - 8;
        });
        y = Math.min(col[0], col[1]);

        tableBlocks.forEach(function (b) {
            var t = b.table;
            var rowH = 11, headH = 13;
            var hNeeded = 16 + headH + t.rows.length * rowH + 8;
            if (y - hNeeded < MARGIN) newPage();
            textLine(MARGIN, y - 10, b.title.toUpperCase(), 8, true, '#444444');
            rule(MARGIN, y - 13, PAGE_W - MARGIN, '#cccccc', 0.5);
            y -= 16;
            var nCols = t.head.length;
            var firstW = Math.min(150, CONTENT_W * 0.28);
            var otherW = (CONTENT_W - firstW) / Math.max(1, nCols - 1);
            function cellX(i) { return i === 0 ? MARGIN : MARGIN + firstW + (i - 1) * otherW; }
            function cellW(i) { return i === 0 ? firstW : otherW; }
            // header
            page.push(rgbOp('#eeeeee', false) + ' ' + num(MARGIN) + ' ' + num(y - headH) + ' ' + num(CONTENT_W) + ' ' + num(headH) + ' re f');
            t.head.forEach(function (hcell, i) {
                var s = fitText(String(hcell), 8, true, cellW(i) - 6);
                var xx = i === 0 ? cellX(i) + 3 : cellX(i) + cellW(i) - 3 - textWidth(s, 8, true);
                textLine(xx, y - 9.5, s, 8, true, '#111111');
            });
            y -= headH;
            t.rows.forEach(function (row, ri) {
                if (y - rowH < MARGIN) {
                    newPage();
                }
                if (ri % 2 === 1) {
                    page.push(rgbOp('#f7f7f7', false) + ' ' + num(MARGIN) + ' ' + num(y - rowH) + ' ' + num(CONTENT_W) + ' ' + num(rowH) + ' re f');
                }
                row.forEach(function (cell, i) {
                    var s = fitText(String(cell), 8, i === 0, cellW(i) - 6);
                    var xx = i === 0 ? cellX(i) + 3 : cellX(i) + cellW(i) - 3 - textWidth(s, 8, false);
                    textLine(xx, y - 8.5, s, 8, i === 0, i === 0 ? '#222222' : '#000000');
                });
                rule(MARGIN, y - rowH, PAGE_W - MARGIN, '#e2e2e2', 0.3);
                y -= rowH;
            });
            y -= 10;
        });

        pages.push(page);

        // Footer on every page
        var footer = spec.footer || 'HHpro Psychrometrics';
        pages.forEach(function (p, i) {
            p.push('BT ' + rgbOp('#777777', false) + ' /F1 7.5 Tf ' + num(MARGIN) + ' ' + num(MARGIN - 16) + ' Td ' +
                pdfString(footer) + ' Tj ET');
            var pn = 'Page ' + (i + 1) + ' of ' + pages.length;
            p.push('BT ' + rgbOp('#777777', false) + ' /F1 7.5 Tf ' + num(PAGE_W - MARGIN - textWidth(pn, 7.5, false)) + ' ' + num(MARGIN - 16) + ' Td ' +
                pdfString(pn) + ' Tj ET');
        });

        return writePdf(pages);
    }

    // ---------------- PDF file assembly ----------------

    function writePdf(pages) {
        var objects = [];   // strings, 1-based object numbers
        function add(s) { objects.push(s); return objects.length; }

        var fontN = add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>');
        var fontB = add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>');
        var pagesN = add('PLACEHOLDER');
        var pageIds = [];
        pages.forEach(function (ops) {
            var content = ops.join('\n');
            var cN = add('<< /Length ' + content.length + ' >>\nstream\n' + content + '\nendstream');
            var pN = add('<< /Type /Page /Parent ' + pagesN + ' 0 R /MediaBox [0 0 ' + PAGE_W + ' ' + PAGE_H + '] ' +
                '/Resources << /Font << /F1 ' + fontN + ' 0 R /F2 ' + fontB + ' 0 R >> ' +
                '/ExtGState << /GA << /ca 0.3 /CA 1 >> >> >> /Contents ' + cN + ' 0 R >>');
            pageIds.push(pN);
        });
        objects[pagesN - 1] = '<< /Type /Pages /Kids [' + pageIds.map(function (n) { return n + ' 0 R'; }).join(' ') +
            '] /Count ' + pageIds.length + ' >>';
        var catalog = add('<< /Type /Catalog /Pages ' + pagesN + ' 0 R >>');

        var out = '%PDF-1.4\n%\xE2\xE3\xCF\xD3\n';
        var offsets = [];
        objects.forEach(function (body, i) {
            offsets.push(out.length);
            out += (i + 1) + ' 0 obj\n' + body + '\nendobj\n';
        });
        var xref = out.length;
        out += 'xref\n0 ' + (objects.length + 1) + '\n0000000000 65535 f \n';
        offsets.forEach(function (o) {
            out += ('0000000000' + o).slice(-10) + ' 00000 n \n';
        });
        out += 'trailer\n<< /Size ' + (objects.length + 1) + ' /Root ' + catalog + ' 0 R >>\nstartxref\n' + xref + '\n%%EOF\n';

        var bytes = new Uint8Array(out.length);
        for (var i = 0; i < out.length; i++) bytes[i] = out.charCodeAt(i) & 0xff;
        return new Blob([bytes], { type: 'application/pdf' });
    }

    HHpro.PsychroPdf = { build: build };
})();
